CREATE TABLE users (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    profile_img_url VARCHAR,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    card_prefix VARCHAR NOT NULL,
    next_card_number BIGINT NOT NULL DEFAULT 1,
    description VARCHAR,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT ck_projects_next_card_number CHECK (next_card_number > 0)
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    provider VARCHAR NOT NULL,
    provider_user_id VARCHAR NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_oauth_accounts PRIMARY KEY (id),
    CONSTRAINT uk_oauth_accounts_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    project_id BIGINT NOT NULL,
    role VARCHAR NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL,
    left_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (id),
    CONSTRAINT uk_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT uk_members_project_id UNIQUE (project_id, id),
    CONSTRAINT fk_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_members_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    title VARCHAR,
    content TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_workspaces PRIMARY KEY (id),
    CONSTRAINT fk_workspaces_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    name VARCHAR,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_boards PRIMARY KEY (id),
    CONSTRAINT uk_boards_project_id UNIQUE (project_id, id),
    CONSTRAINT fk_boards_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    member_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    board_id BIGINT NOT NULL,
    title VARCHAR NOT NULL,
    content TEXT NOT NULL,
    username VARCHAR,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id),
    CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cards_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_cards_project_member FOREIGN KEY (project_id, member_id)
        REFERENCES members (project_id, id),
    CONSTRAINT fk_cards_project_board FOREIGN KEY (project_id, board_id)
        REFERENCES boards (project_id, id)
);
